name: Fly
version: 3.1.0
main: io.omoli822.fly.Fly
api-version: 1.21

commands:
  setjoinmessage:
    description: "Allows you to set the join message. Use ${player.name} to insert the player name."
    usage: /setjoinmessage <message>
    permission: fly.admin

  flyreload:
    description: Reloads the Fly plugin config
    usage: /flyreload
    permission: fly.reload

  flyeco:
    description: Access the admin economy GUI
    usage: /admintools
    permission: fly.ecoadmin
